import House1 from '@assets/House1.jpg';
import House2 from '@assets/House2.jpg';
import House3 from '@assets/House3.jpg';
import House4 from '@assets/House4.jpg';
import House5 from '@assets/House5.jpg';
import House6 from '@assets/House6.jpg';
import House7 from '@assets/House7.jpg';
import House8 from '@assets/House8.jpg';
import House9 from '@assets/House9.jpg';
import House10 from '@assets/House10.jpg';
import House11 from '@assets/House11.jpg';

export const mockHouses = [
  {
    _id: '6415a382639074f7ae54d796',
    houseName: 'Bondhusvatnet',
    address: 'Bondhusvatnet',
    lake: 'Bondhusvatnet',
    price: 'Bondhusvatnet',
    persons: '',
    geoData: '',
    booking: [
      {
        CHECK_IN: 1682197200000,
        CHECK_OUT: 1682542800000,
      },
      {
        CHECK_IN: 1684098000000,
        CHECK_OUT: 1684616400000,
      },
    ],
    image: [House1],
    rating: {
      oneStar: ['star'],
      twoStar: [],
      threeStar: ['star', 'star'],
      fourStar: [],
      fiveStar: [],
    },
    __v: 0,
  },
  {
    _id: '6415a385639074f7ae54d798',
    houseName: 'Bondhusvatnet',
    address: 'Bondhusvatnet',
    lake: 'Bondhusvatnet',
    price: 'Bondhusvatnet',
    persons: '',
    geoData: '',
    booking: [],
    image: [House2],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a386639074f7ae54d79a',
    houseName: 'Bondhusvatnet',
    address: 'Bondhusvatnet',
    lake: 'Bondhusvatnet',
    price: 'Bondhusvatnet',
    persons: '',
    geoData: '',
    booking: [],
    image: [House3],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3a4639074f7ae54d79c',
    houseName: 'Mjosa',
    address: 'Mjosa',
    lake: 'Mjosa',
    price: 'Mjosa',
    persons: 'Mjosa',
    geoData: 'Mjosa',
    booking: [],
    image: [House4],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3a5639074f7ae54d79e',
    houseName: 'Mjosa',
    address: 'Mjosa',
    lake: 'Mjosa',
    price: 'Mjosa',
    persons: 'Mjosa',
    geoData: 'Mjosa',
    booking: [],
    image: [House5],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3a6639074f7ae54d7a0',
    houseName: 'Mjosa',
    address: 'Mjosa',
    lake: 'Mjosa',
    price: 'Mjosa',
    persons: 'Mjosa',
    geoData: 'Mjosa',
    booking: [],
    image: [House6],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3b2639074f7ae54d7a2',
    houseName: 'Hornindalsvatnet',
    address: 'Hornindalsvatnet',
    lake: 'Hornindalsvatnet',
    price: 'Hornindalsvatnet',
    persons: 'Hornindalsvatnet',
    geoData: 'Hornindalsvatnet',
    booking: [],
    image: [House7],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3b2639074f7ae54d7a4',
    houseName: 'Hornindalsvatnet',
    address: 'Hornindalsvatnet',
    lake: 'Hornindalsvatnet',
    price: 'Hornindalsvatnet',
    persons: 'Hornindalsvatnet',
    geoData: 'Hornindalsvatnet',
    booking: [],
    image: [House8],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3b3639074f7ae54d7a6',
    houseName: 'Hornindalsvatnet',
    address: 'Hornindalsvatnet',
    lake: 'Hornindalsvatnet',
    price: 'Hornindalsvatnet',
    persons: 'Hornindalsvatnet',
    geoData: 'Hornindalsvatnet',
    booking: [],
    image: [House9],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3b3639074f7ae54d7a8',
    houseName: 'Hornindalsvatnet',
    address: 'Hornindalsvatnet',
    lake: 'Hornindalsvatnet',
    price: 'Hornindalsvatnet',
    persons: 'Hornindalsvatnet',
    geoData: 'Hornindalsvatnet',
    booking: [],
    image: [House10],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3b4639074f7ae54d7aa',
    houseName: 'Hornindalsvatnet',
    address: 'Hornindalsvatnet',
    lake: 'Hornindalsvatnet',
    price: 'Hornindalsvatnet',
    persons: 'Hornindalsvatnet',
    geoData: 'Hornindalsvatnet',
    booking: [],
    image: [House11],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
];
