export const mockHouses = [
  {
    _id: '6415a382639074f7ae54d796',
    houseName: 'Bondhusvatnet',
    address: 'Bondhusvatnet',
    lake: 'Bondhusvatnet',
    price: 'Bondhusvatnet',
    persons: '',
    geoData: '',
    booking: [],
    image: ['images/9d147f22-2da4-4d9d-b746-dc5a3b033e70.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a385639074f7ae54d798',
    houseName: 'Bondhusvatnet',
    address: 'Bondhusvatnet',
    lake: 'Bondhusvatnet',
    price: 'Bondhusvatnet',
    persons: '',
    geoData: '',
    booking: [],
    image: ['images/f4f8aafb-1c3e-4c4d-b53b-cc09d0688c06.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a386639074f7ae54d79a',
    houseName: 'Bondhusvatnet',
    address: 'Bondhusvatnet',
    lake: 'Bondhusvatnet',
    price: 'Bondhusvatnet',
    persons: '',
    geoData: '',
    booking: [],
    image: ['images/1308c680-c351-4fd7-85ac-09b1d2df230b.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3a4639074f7ae54d79c',
    houseName: 'Mjosa',
    address: 'Mjosa',
    lake: 'Mjosa',
    price: 'Mjosa',
    persons: 'Mjosa',
    geoData: 'Mjosa',
    booking: [],
    image: ['images/9a5eb36e-3b7b-470c-9d54-86363211f28f.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3a5639074f7ae54d79e',
    houseName: 'Mjosa',
    address: 'Mjosa',
    lake: 'Mjosa',
    price: 'Mjosa',
    persons: 'Mjosa',
    geoData: 'Mjosa',
    booking: [],
    image: ['images/2f9f88c3-a078-43d9-a010-27658cb87ae9.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3a6639074f7ae54d7a0',
    houseName: 'Mjosa',
    address: 'Mjosa',
    lake: 'Mjosa',
    price: 'Mjosa',
    persons: 'Mjosa',
    geoData: 'Mjosa',
    booking: [],
    image: ['images/c6670565-afec-481d-b4e9-4faf54ed0a19.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3b2639074f7ae54d7a2',
    houseName: 'Hornindalsvatnet',
    address: 'Hornindalsvatnet',
    lake: 'Hornindalsvatnet',
    price: 'Hornindalsvatnet',
    persons: 'Hornindalsvatnet',
    geoData: 'Hornindalsvatnet',
    booking: [],
    image: ['images/bf539051-5a85-41c3-8779-33496507f0f9.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3b2639074f7ae54d7a4',
    houseName: 'Hornindalsvatnet',
    address: 'Hornindalsvatnet',
    lake: 'Hornindalsvatnet',
    price: 'Hornindalsvatnet',
    persons: 'Hornindalsvatnet',
    geoData: 'Hornindalsvatnet',
    booking: [],
    image: ['images/96864e53-6555-48ce-80a9-222fe994eba9.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3b3639074f7ae54d7a6',
    houseName: 'Hornindalsvatnet',
    address: 'Hornindalsvatnet',
    lake: 'Hornindalsvatnet',
    price: 'Hornindalsvatnet',
    persons: 'Hornindalsvatnet',
    geoData: 'Hornindalsvatnet',
    booking: [],
    image: ['images/2c6e2d1c-4d07-49b4-8139-caf272ce129e.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3b3639074f7ae54d7a8',
    houseName: 'Hornindalsvatnet',
    address: 'Hornindalsvatnet',
    lake: 'Hornindalsvatnet',
    price: 'Hornindalsvatnet',
    persons: 'Hornindalsvatnet',
    geoData: 'Hornindalsvatnet',
    booking: [],
    image: ['images/967ea7ba-c0c9-4e62-977d-0e609dd4b232.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
  {
    _id: '6415a3b4639074f7ae54d7aa',
    houseName: 'Hornindalsvatnet',
    address: 'Hornindalsvatnet',
    lake: 'Hornindalsvatnet',
    price: 'Hornindalsvatnet',
    persons: 'Hornindalsvatnet',
    geoData: 'Hornindalsvatnet',
    booking: [],
    image: ['images/86f15f3e-7b90-4efe-8b6a-204f243045ff.jpg'],
    rating: { oneStar: [], twoStar: [], threeStar: [], fourStar: [], fiveStar: [] },
    __v: 0,
  },
];
